### ISSUE TITLE
Historie

### ISSUE THREAD

**Issue by tuetschek** [b0r3k/dialogue-planner#3]
Asi by nešlo zrušit ty názvy větví hwX? To je kdyžtak jen detail...

**Comment by b0r3k** [comment]
No jakoby člověk by musel nějak přepsat staré commity.. nejtemnější zákoutí gitu, do kterých bych se nepouštěl, jsem rád, že jsem se předtím popral s tou historií alespoň nějak. 😅 Možná to nějak jde, ale zabralo by to naprosto neúměrně času.
