### ISSUE TITLE
Google ID

### ISSUE THREAD

**Issue by tuetschek** [b0r3k/dialogue-planner#4]
Aktuálně to sice podporuje víc konverzací, ale pro všechny uživatele to má stejné google ID? Nešlo by zmínit google ID na začátku konverzace? (Netuším, jak těžké by tohle bylo)

**Comment by b0r3k** [comment]
Google ID a credentials potřebuje Dialogue Policy, takže jsou spojené s instancí Dialogue Handleru. Možná by šlo, aby každý uživatel měl svůj Dialogue Handler, který bych serializoval, podívám se na to.

**Comment by b0r3k** [comment]
Změněno, `server.py` si ve slovníku pamatuje i vlastní Dialogue Handler, takže každý může být provázaný s jiným účtem. Akorát to pak samozřejmě nepodporuje to ukládání tokenu, tak jsem tomu vytvořit vlastní Policy a Config.
